[package]
authors = ['Thales']
edition = '2018'
homepage = 'https://thales.network'
license = 'GPL-3.0-only'
name = 'account'
repository = 'https://github.com/Thales-network/thales/'
version = '0.1.1'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", default-features = false, optional = true, features = ["derive"] }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
log = "0.4"
hex = { version = "0.4", default-features = false }
sha3 = { version = "0.8", default-features = false }

blake2-rfc = { version = "0.2.18", default-features = false, optional = true }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }

sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"serde/std",
	"hex/std",
	"sha3/std",

	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",

	"full_crypto",
]

full_crypto = [
	"blake2-rfc",
	"sp-runtime-interface/disable_target_static_assertions",
]
