[package]
name = "thales-rpc-trace"
version = '0.6.0'
authors = ['Thales']
edition = '2018'
homepage = 'https://thales.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/Thales-network/thales/'

[dependencies]
# Utils
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.8"
ethereum-types = "0.11.0"
ethereum = { git = "https://github.com/notlesh/ethereum", branch = "notlesh-moonbeam-v0.6", features = ["with-codec"] }

# Async and logs
tokio = { version = "0.2.13", features = ["sync", "time"]}
futures = { version = "0.3", features = ["compat"] }
tracing = "0.1.25"

# Primitives
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-utils = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
fp-rpc = { git = "https://github.com/purestake/frontier", branch = "notlesh-moonbeam-v0.7" }
thales-rpc-primitives-debug = { path = "../../../primitives/rpc/debug" }

# Client and RPC
jsonrpc-core = "15.0.0"
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-transaction-graph = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
fc-rpc = { git = "https://github.com/purestake/frontier", branch = "notlesh-moonbeam-v0.7" }
fc-consensus = { git = "https://github.com/purestake/frontier", branch = "notlesh-moonbeam-v0.7" }
fc-rpc-core = { git = "https://github.com/purestake/frontier", branch = "notlesh-moonbeam-v0.7" }
thales-rpc-core-trace = { path = "../../rpc-core/trace" }