[package]
name = "precompiles"
version = "0.6.0"
authors = ["Thales"]
edition = "2018"

[dependencies]
log = "0.4"
# This is need to overcome the double importing of rand 0.5.6 in substrate-bn with and without std
# https://github.com/rust-random/rand/issues/645
rand = { version = "0.5.6", default-features = false }
rustc-hex = { version = "2.0.1", default-features = false }

codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
evm = { version = "0.26.0", default-features = false, features = ["with-codec"] }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
pallet-evm = { git = "https://github.com/purestake/frontier", default-features = false, branch = "notlesh-moonbeam-v0.7" }
pallet-evm-precompile-bn128 = { git = "https://github.com/purestake/frontier", default-features = false, branch = "notlesh-moonbeam-v0.7" }
pallet-evm-precompile-dispatch = { git = "https://github.com/purestake/frontier", default-features = false, branch = "notlesh-moonbeam-v0.7" }
pallet-evm-precompile-modexp = { git = "https://github.com/purestake/frontier", default-features = false, branch = "notlesh-moonbeam-v0.7" }
pallet-evm-precompile-simple = { git = "https://github.com/purestake/frontier", default-features = false, branch = "notlesh-moonbeam-v0.7" }
pallet-evm-precompile-sha3fips = { git = "https://github.com/purestake/frontier", default-features = false, branch = "notlesh-moonbeam-v0.7" }
parachain-staking = { path = "../../pallets/parachain-staking", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }

[dev-dependencies]
hex = "0.4"

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"evm/std",
	"sp-std/std",
	"sp-core/std",
	"rand/std",
	"pallet-evm-precompile-bn128/std",
	"pallet-evm-precompile-dispatch/std",
	"pallet-evm-precompile-modexp/std",
	"pallet-evm-precompile-simple/std",
	"parachain-staking/std",
	"frame-system/std",
	"pallet-evm-precompile-sha3fips/std",
]
